---
- hosts: '{{ hosts }}'
  vars:

  tasks:
    - name: create ssh key
      shell: ssh-keygen -t rsa -f /root/.ssh/id_rsa -P ''
    - name: copy ssh key to ansible
      synchronize: src=/root/.ssh/id_rsa.pub dest=/test/keys/{{ ansible_nodename }}.pub mode=pull
